name: 'dox-dev'
networks:
  dox_net:

services:
  dox_app:
    image: node:16.13.1
    volumes:
      - ../../:/src/
    working_dir: /src
    command: npx nodemon --ignore docker/docker-compose/data/* --ignore public/js/views.js server.js

    container_name: dox_app-dev
    restart: unless-stopped
    ports:
      - "80:8888"
    networks:
      - dox_net

    depends_on:
      - mongodb
    env_file:
      - ../../.env
    environment:
      - LISTEN_PORT=8888
      - ENDPOINT_URL=http://localhost:8888
      - MAILSERVER_SENDER_ADDRESS=
      - MAILSERVER_HOST=
      - MAILSERVER_PORT=
      - MAILSERVER_PASSWORD=
      - MAILSERVER_USER=
      - MONGODB_URI=mongodb://root:root@dox_db-dev:27017


  mongodb:
    image: mongo:7.0.0-rc7
    container_name: dox_db-dev
    restart: unless-stopped
    expose:
      - "27017:27017"
    networks:
      - dox_net
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dox_db